## Importing Dependencies

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Loading dataset

In [21]:
cols = ['Time','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10',
        'V11','V12','V13','V14','V15','V16','V17','V18','V19',
        'V20','V21','V22','V23','V24','V25','V26','V27','V28',
        'Amount','Class']

credit_card_data = pd.read_csv(
    "/content/creditcard.csv",
    on_bad_lines='skip',
    names=cols,
    header=0
)
credit_card_data

       Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     45026  1.167275  0.268688  0.387962  ...  0.026024  0.020027    9.82    0.0
1     45026 -0.661165  0.849284  0.919841  ... -0.277936 -0.287520    4.70    0.0
2     45028  1.053638 -0.389468  1.165457  ...  0.002712  0.038287   74.99    0.0
3     45029  1.434427 -0.532762 -0.157947  ... -0.016381 -0.000267   25.20    0.0
4     45029 -0.740071  0.388858  1.499736  ... -0.094327 -0.160285   76.00    0.0
...     ...       ...       ...       ...  ...       ...       ...     ...    ...
5940  35633  0.786689 -0.691214 -0.329291  ... -0.001435  0.025559  200.00    0.0
5941  35633  0.800996 -2.159993  0.008378  ... -0.024151  0.077021  363.00    0.0
5942  35633  1.115726 -0.472602  0.983034  ... -0.060566  0.003541   36.92    0.0
5943  35634  1.239103 -1.000617  0.843324  ...  0.036574  0.035202   91.00    0.0
5944  35634  1.374193 -0.720679  0.891375  ...       NaN       NaN     NaN    NaN

[5945 rows x 31 columns]

In [22]:
credit_card_data.head()

    Time        V1        V2        V3  ...       V27       V28  Amount  Class
0  45026  1.167275  0.268688  0.387962  ...  0.026024  0.020027    9.82    0.0
1  45026 -0.661165  0.849284  0.919841  ... -0.277936 -0.287520    4.70    0.0
2  45028  1.053638 -0.389468  1.165457  ...  0.002712  0.038287   74.99    0.0
3  45029  1.434427 -0.532762 -0.157947  ... -0.016381 -0.000267   25.20    0.0
4  45029 -0.740071  0.388858  1.499736  ... -0.094327 -0.160285   76.00    0.0

[5 rows x 31 columns]

In [23]:
credit_card_data.tail()

       Time        V1        V2        V3  ...       V27       V28  Amount  Class
5940  35633  0.786689 -0.691214 -0.329291  ... -0.001435  0.025559  200.00    0.0
5941  35633  0.800996 -2.159993  0.008378  ... -0.024151  0.077021  363.00    0.0
5942  35633  1.115726 -0.472602  0.983034  ... -0.060566  0.003541   36.92    0.0
5943  35634  1.239103 -1.000617  0.843324  ...  0.036574  0.035202   91.00    0.0
5944  35634  1.374193 -0.720679  0.891375  ...       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [24]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5945 entries, 0 to 5944
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    5945 non-null   int64
 1   V1      5945 non-null   float64
 2   V2      5945 non-null   float64
 3   V3      5945 non-null   float64
 4   V4      5945 non-null   float64
 5   V5      5945 non-null   float64
 6   V6      5944 non-null   float64
 7   V7      5944 non-null   float64
 8   V8      5944 non-null   float64
 9   V9      5944 non-null   float64
 10  V10     5944 non-null   float64
 11  V11     5944 non-null   float64
 12  V12     5944 non-null   float64
 13  V13     5944 non-null   float64
 14  V14     5944 non-null   float64
 15  V15     5944 non-null   float64
 16  V16     5944 non-null   float64
 17  V17     5944 non-null   float64
 18  V18     5944 non-null   float64
 19  V19     5944 non-null   float64
 20  V20     5944 non-null   float64
 21  V21     5944 non-null   float64
 22  V22     5944 non-null   float64
 23  V23     5944 non-null   float64
 24  V24     5944 non-null   float64
 25  V25     5944 non-null   float64
 26  V26     5944 non-null   float64
 27  V27     5944 non-null   float64
 28  V28     5944 non-null   float64
 29  Amount  5944 non-null   float64
 30  Class   5944 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.4 MB

### checking missing values

In [25]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64


## As we have missing values in our dataet so we will fill with mode

In [28]:
credit_card_data.fillna(credit_card_data.mode().iloc[0], inplace=True)

In [29]:
credit_card_data

       Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     45026  1.167275  0.268688  0.387962  ...  0.026024  0.020027    9.82    0.0
1     45026 -0.661165  0.849284  0.919841  ... -0.277936 -0.287520    4.70    0.0
2     45028  1.053638 -0.389468  1.165457  ...  0.002712  0.038287   74.99    0.0
3     45029  1.434427 -0.532762 -0.157947  ... -0.016381 -0.000267   25.20    0.0
4     45029 -0.740071  0.388858  1.499736  ... -0.094327 -0.160285   76.00    0.0
...     ...       ...       ...       ...  ...       ...       ...     ...    ...
5940  35633  0.786689 -0.691214 -0.329291  ... -0.001435  0.025559  200.00    0.0
5941  35633  0.800996 -2.159993  0.008378  ... -0.024151  0.077021  363.00    0.0
5942  35633  1.115726 -0.472602  0.983034  ... -0.060566  0.003541   36.92    0.0
5943  35634  1.239103 -1.000617  0.843324  ...  0.036574  0.035202   91.00    0.0
5944  35634  1.374193 -0.720679  0.891375  ...  0.241305 -0.020359    1.00    0.0

[5945 rows x 31 columns]

In [30]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [34]:
credit_card_data['Class'].value_counts()

Class
0.0    5941
1.0       4
Name: count, dtype: int64

## As this dataset is highly unbalanced

In [48]:
# seeparting fraud and real transaction for analysis
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]
print(legit.shape)
print(fraud.shape)

(5941, 31)
(4, 31)

In [49]:
## statistical analysis
legit.Amount.describe()

count    5941.000000
mean       91.449980
std       220.087229
min         0.000000
25%         4.490000
50%        21.970000
75%        81.980000
max      3669.000000
Name: Amount, dtype: float64

In [50]:
fraud.Amount.describe()

count      4.000000
mean      27.187500
std       52.535122
min        0.760000
25%        0.940000
50%        1.000000
75%       27.247500
max      105.990000
Name: Amount, dtype: float64

In [51]:
## comparing the values for both transaction
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28    Amount
Class                                    ...
0.0    27703.520451 -0.232377  0.017610  ...  0.019567  0.008596  91.44998
1.0    43022.500000 -1.003286  1.492504  ...  0.283671 -0.009684  27.18750

[2 rows x 30 columns]

In [62]:
## building sample data set contaning simple distrbution
legit_sample=legit.sample(n=492)

In [71]:
# concatenating both samplesa
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [72]:
new_dataset.head()

       Time        V1        V2        V3  ...       V27       V28  Amount  Class
2179   1704 -4.646614  3.215190 -1.495760  ...  0.614593  0.127344     1.0    0.0
45    45050  1.152283 -0.901053  0.788004  ...  0.025156  0.037117   100.0    0.0
4891  35137 -1.244891  0.888219  2.096254  ...  0.237226  0.044968    45.0    0.0
3560   3049  1.082308 -0.096797  1.048255  ...  0.067915  0.025731    15.0    0.0
3358   2911 -0.299876  0.620890  0.731033  ...  0.231522 -0.024235     1.0    0.0

[5 rows x 31 columns]

In [73]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0      4
Name: count, dtype: int64

## Resamplying because the data set is highly unbalanced

In [109]:
from sklearn.utils import resample


# legit sample (already 492)
legit_sample = legit.sample(n=492, random_state=42)

# fraud ko 492 tak upsample karo
fraud_upsampled = resample(fraud,
                          replace=True,   # important
                          n_samples=492,
                          random_state=42)

# combine
new_dataset = pd.concat([legit_sample, fraud_upsampled])

# check
print(new_dataset['Class'].value_counts())

Class
0.0    492
1.0    492
Name: count, dtype: int64

In [77]:
a=new_dataset.groupby('Class').mean
a

## splitting the data in to featurres and target

In [78]:
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [79]:
X

       Time        V1        V2        V3  ...       V26       V27       V28  Amount
5799  35569  1.262437 -0.395376  0.173762  ... -0.304650  0.036245  0.030057   25.52
1626  45867 -0.706617  1.206502  1.021766  ... -0.337364  0.065188  0.081369   19.29
3432   2936  1.218089 -0.138280  0.047949  ... -0.599769  0.049815  0.005190    1.00
2122   1639  1.215606  0.335834  0.285748  ... -0.330860  0.012530  0.023501   19.30
2688   2237 -0.760536  1.297768  1.199296  ...  0.072822  0.139275  0.058839    8.99
...     ...       ...       ...       ...  ...       ...       ...       ...     ...
5833  35585 -2.019001  1.491270  0.005222  ...  0.523601  0.626283  0.152440    0.76
875   45463 -1.476893  2.122314 -1.229470  ... -0.569232  0.481019 -0.047555    1.00
875   45463 -1.476893  2.122314 -1.229470  ... -0.569232  0.481019 -0.047555    1.00
5833  35585 -2.019001  1.491270  0.005222  ...  0.523601  0.626283  0.152440    0.76
875   45463 -1.476893  2.122314 -1.229470  ... -0.569232  0.481019 -0.047555    1.00

[984 rows x 30 columns]

In [80]:
Y

5799    0.0
1626    0.0
3432    0.0
2122    0.0
2688    0.0
       ...
5833    1.0
875     1.0
875     1.0
5833    1.0
875     1.0
Name: Class, Length: 984, dtype: float64

## splitting in to training and tsting

In [81]:
### fr traning
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [82]:
X.shape,X_train.shape,X_test.shape

((984, 30), (787, 30), (197, 30))

## model training

In [84]:
model=LogisticRegression()

In [85]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

## Model Evaluation

In [86]:
# accuracy_score on training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [94]:
print(f"Accuracy score on training data:",training_data_accuracy)

Accuracy score on training data: 0.9733163913595934

In [95]:
## accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [96]:
print(f"Accuracy score on testing data:",test_data_accuracy)

Accuracy score on testing data: 0.9949238578680203

# now making function to check the legiit  or fraud transaction of data

In [104]:
def predict_transaction(input_data):
    prediction = model.predict([input_data])

    if prediction[0] == 0:
        return "Legit Transaction"
    else:
        return "Fraud Transaction"

In [105]:
print(predict_transaction(X_test.iloc[0].values))

Fraud Transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [106]:
print(predict_transaction(X_test.iloc[1].values))

Legit Transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [107]:
print(predict_transaction(X_test.iloc[3].values))

Legit Transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [108]:
print(predict_transaction(X_test.iloc[4].values))

Fraud Transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(